//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace UrbanSpotsWcfService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "User", Namespace = "http://schemas.datacontract.org/2004/07/UrbanSpotsWcfService")]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Guid UserGuidField;

        private string UserNameField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid UserGuid
        {
            get
            {
                return this.UserGuidField;
            }
            set
            {
                this.UserGuidField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IUrbanSpotsWcf")]
public interface IUrbanSpotsWcf
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUrbanSpotsWcf/GetData", ReplyAction = "http://tempuri.org/IUrbanSpotsWcf/GetDataResponse")]
    string GetData(int value);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUrbanSpotsWcf/LoginUser", ReplyAction = "http://tempuri.org/IUrbanSpotsWcf/LoginUserResponse")]
    UrbanSpotsWcfService.User LoginUser(string email, string pass);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IUrbanSpotsWcf/AddLocation", ReplyAction = "http://tempuri.org/IUrbanSpotsWcf/AddLocationResponse")]
    string AddLocation(string authorGuid, string name, string description, double lng, double lat, byte[] photo);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IUrbanSpotsWcfChannel : IUrbanSpotsWcf, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class UrbanSpotsWcfClient : System.ServiceModel.ClientBase<IUrbanSpotsWcf>, IUrbanSpotsWcf
{

    public UrbanSpotsWcfClient()
    {
    }

    public UrbanSpotsWcfClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public UrbanSpotsWcfClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public UrbanSpotsWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public UrbanSpotsWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }

    public UrbanSpotsWcfService.User LoginUser(string email, string pass)
    {
        return base.Channel.LoginUser(email, pass);
    }

    public string AddLocation(string authorGuid, string name, string description, double lng, double lat, byte[] photo)
    {
        return base.Channel.AddLocation(authorGuid, name, description, lng, lat, photo);
    }
}

    
